name: Automated Tests

on:
  push:
   branches: 
    - 'main'
  # schedule:
  #   - cron: '0 0 * * *'  # Schedule to run every day at midnight UTC

jobs:
  build:
    name: Login Tests
    runs-on: ubuntu-latest
    environment: tst
    env:
      MY_URL: ${{ vars.MY_URL }}
      USER_NAME: ${{ secrets.USER_NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Get node version
      id: node
      run: |
        echo "::set-output name=version::$(node -v)"

    - name: Get node_modules cache
      uses: actions/cache@v3.0.2
      id: node_modules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}
    #   with:
    #     node-version: '18'
    #     cache: 'npm'
    #     cache-dependency-path: package-lock.json
    # - run: npm install #npx playwright install  
    # - run: npx playwright install

    - name: Run login tests
      run: npx codeceptjs run --grep "@lambda-login" --steps   # Replace with the command to run your tests
