name: Automated Tests

on:
  push:
   branches: 
    - 'main'
  # schedule:
  #   - cron: '0 0 * * *'  # Schedule to run every day at midnight UTC

jobs:
  build:
    name: Login Tests
    runs-on: ubuntu-latest
    environment: tst
    env:
      MY_URL: ${{ vars.MY_URL }}
      USER_NAME: ${{ secrets.USER_NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache node modules
      id: myCache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    - name: Install dependencies
      if: steps.myCache.outputs.cache-hit != 'true'
      run: npm install #npx playwright install  

    - name: Install playwirght
      run: npx playwright install

    - name: Run login tests
      run: npx codeceptjs run --grep "@lambda-login" --steps   # Replace with the command to run your tests
